insert into product(name, category, price, manufacturer, stock, description) values ("볼펜", "잡화", 50000, "모나미", 20, "최고급 볼펜")
insert into product(name, category, price, manufacturer, stock, description) values ("가방", "잡화", 200000, "아디다스", 10, "최고급 가방")
insert into product(name, category, price, manufacturer, stock, description) values ("이어폰", "전자", 30000, "소니", 4, "최고급 이어폰")
insert into product(name, category, price, manufacturer, stock, description) values ("필통", "잡화", 1100, "모나미", 100, "최고급 필통")
insert into product(name, category, price, manufacturer, stock, description) values ("잡지", "도서", 10000, "영풍문고", 20, "최고급 잡지")
insert into product(name, category, price, manufacturer, stock, description) values ("휴지", "생활", 4000, "컬처랜드", 100, "최고급 휴지")
insert into product(name, category, price, manufacturer, stock, description) values ("초콜렛","식품", 2000, "가나", 220, "최고급 초콜렛")
insert into product(name, category, price, manufacturer, stock, description) values ("사탕", "식품", 1000, "롯데", 230, "최고급 사탕")
insert into product(name, category, price, manufacturer, stock, description) values ("전화기", "가전", 140000, "소니", 20, "최고급 전화기")
insert into product(name, category, price, manufacturer, stock, description) values ("연필", "잡화", 50000, "모나미", 20, "최고급 볼펜")
